const REQUEST_POST = "REQUEST_POST";
const RECEIVED_POST = "RECEIVED_POST";
const GET_ALL_ANIMALS = "GET_ALL_ANIMALS";
const GET_ANIMAl_BY_ID = "GET_ANIMAl_BY_ID";
const FIND_ANIMAL_BY_TYPE = "FIND_ANIMAL_BY_TYPE";

export {
    REQUEST_POST,
    RECEIVED_POST,
    GET_ALL_ANIMALS,
    GET_ANIMAl_BY_ID,
    FIND_ANIMAL_BY_TYPE,
};